name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # install all depedencies
      - name: Install depedencies
        run: ./installDependencies.sh

      # Compile the code
      - name: Build project
        run: make

      - name: Remove binary after build
        run: make clean

  test_suite:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC and CUnit
        run: ./installDependencies.sh

      - name: Compile unit tests (suite 1)
        run: make test_suite

      - name: Run unit tests (suite 1)
        run: ./test_suite  # Exécution de la première suite de tests

      - name: Remove test binary after execution
        run: make clean
