name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # install all depedencies
      - name: Install depedencies
        run: ./.github/workflows/installDependencies.sh

      # Compile the code
      # - name: Build project
        # run: make

      # Run tests
      - name: Run tests
        run: make test
