# name: C Project CI
#
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#
#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       # install all depedencies
#       - name: Install depedencies
#         run: ./installDependencies.sh
#
#       # Compile the code
#       - name: Build project
#         run: make
#
#       - name: Remove binary after build
#         run: make clean
#
#   test_suite:
#     runs-on: ubuntu-latest
#     needs: build
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Install GCC and CUnit
#         run: ./installDependencies.sh
#
#       - name: Compile unit tests (suite 1)
#         run: make test_suite
#
#       - name: Run unit tests (suite 1)
#         run: ./test_suite  # Exécution de la première suite de tests
#
#       - name: Remove test binary after execution
#         run: make clean
#
name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_main:
    name: Build Principal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libsdl2-2.0-0 libsdl2-dev # install SDL2

      - name: Build the project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Archive the build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: build/

  build_with_tests:
    name: Build avec les tests
    runs-on: ubuntu-latest
    needs: build_main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2 and CUnit dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libsdl2-2.0-0 libsdl2-dev # install SDL2
          sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev # install Cunit

      - name: Build the project with tests
        run: |
          mkdir -p build
          cd build
          cmake -DTESTS=ON ..
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_with_tests_artifacts
          path: build/

  run_tests:
    name: Exécution des tests unitaires
    runs-on: ubuntu-latest
    needs: build_with_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libsdl2-2.0-0 libsdl2-dev # install SDL2
          sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev # install Cunit

      - name: Run tests
        run: |
          cd build
          ./testsuite
